In [6]:
import data
from torch import nn, optim
import torch
from tqdm import tqdm

In [7]:
model = nn.Sequential(
    nn.Conv1d(in_channels=1, out_channels=4, kernel_size=2), 
    nn.Conv1d(in_channels=4, out_channels=4, kernel_size=2),
    nn.MaxPool1d(kernel_size=2),
    nn.Flatten(),
    nn.LazyLinear(out_features=5), nn.Sigmoid(),
    nn.LazyLinear(out_features=3),
)

In [8]:
train_music_loader = data.get_data()
loss_fn = nn.MSELoss()# compute the error 
optim_fn = optim.SGD(model.parameters(),lr=0.01) # Stochastic Gradient descent
for epoch in tqdm(range(200)):
    for xb,yb in train_music_loader: # 
        ypred = model(xb) # find the output of the model
        loss = loss_fn(ypred, yb)  #Out is the ML think is the answer, yb the real answer 
        optim_fn.zero_grad() # get ready for the slope
        loss.backward()# find where is it down the slope
        optim_fn.step()# Take a step down
        
if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")


100%|██████████| 200/200 [00:15<00:00, 12.54it/s]


In [9]:
train_music_loader = data.get_data()
for xb,yb in train_music_loader: # 
        ypred = model(xb) # find the output of the model
        print(ypred)

tensor([[0.2107, 0.4008, 0.6261]], grad_fn=<AddmmBackward0>)
tensor([[0.4034, 0.4663, 0.5205]], grad_fn=<AddmmBackward0>)
tensor([[0.5461, 0.3025, 0.3771]], grad_fn=<AddmmBackward0>)
tensor([[0.4832, 0.7819, 0.5673]], grad_fn=<AddmmBackward0>)
tensor([[0.4698, 0.3312, 0.4351]], grad_fn=<AddmmBackward0>)
tensor([[0.2477, 0.0791, 0.4969]], grad_fn=<AddmmBackward0>)
tensor([[0.3361, 0.5682, 0.5947]], grad_fn=<AddmmBackward0>)
tensor([[0.2736, 0.0390, 0.4678]], grad_fn=<AddmmBackward0>)
tensor([[0.4876, 0.7705, 0.5622]], grad_fn=<AddmmBackward0>)
tensor([[0.4565, 0.3394, 0.4459]], grad_fn=<AddmmBackward0>)
tensor([[0.5040, 0.5235, 0.4737]], grad_fn=<AddmmBackward0>)
tensor([[0.5056, 0.3097, 0.4051]], grad_fn=<AddmmBackward0>)
tensor([[0.5947, 0.8808, 0.5308]], grad_fn=<AddmmBackward0>)
tensor([[0.4677, 0.2167, 0.3999]], grad_fn=<AddmmBackward0>)
tensor([[0.5842, 0.4900, 0.4128]], grad_fn=<AddmmBackward0>)
tensor([[0.4115, 0.7065, 0.5881]], grad_fn=<AddmmBackward0>)
tensor([[0.2887, 0.0488,

In [ ]:
from csound_module import Csound_instrument
import os
import numpy as np

csound = Csound_instrument()
os.makedirs("output", exist_ok=True)



for i in range(10):
    idx = i % len(data.params_list)
    params = data.params_list[idx]
    
    # Add small random variation
    freq = params['freq'] + np.random.uniform(-20, 20)
    dur = params['dur'] + np.random.uniform(-0.1, 0.1)
    
    freq = max(220, min(900, freq))  # Keep in range
    dur = max(0.5, min(1.5, dur))
    csound.csound_instrument_score(1, freq, dur, save_file=f"output/ml_generated_{i}.wav")
    print(f"{i}: freq={freq:.1f}Hz, dur={dur:.2f}s (from training sample {idx})")


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.067 T  1.067 TT  1.067 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.003s, CPU: 0.003s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


Using training data to generate varied outputs...
0: freq=233.8Hz, dur=1.07s (from training sample 0)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.902 T  0.902 TT  0.902 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


1: freq=428.5Hz, dur=0.90s (from training sample 1)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.500 T  0.500 TT  0.500 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


2: freq=894.2Hz, dur=0.50s (from training sample 2)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.500 T  1.500 TT  1.500 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.004s, CPU: 0.004s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


3: freq=316.0Hz, dur=1.50s (from training sample 3)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.894 T  0.895 TT  0.895 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


4: freq=540.4Hz, dur=0.89s (from training sample 4)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.635 T  0.635 TT  0.635 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


5: freq=246.9Hz, dur=0.64s (from training sample 5)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.220 T  1.220 TT  1.220 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.003s, CPU: 0.003s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


6: freq=305.7Hz, dur=1.22s (from training sample 6)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.551 T  0.551 TT  0.551 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


7: freq=368.6Hz, dur=0.55s (from training sample 7)


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.318 T  1.318 TT  1.318 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.003s, CPU: 0.003s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)


8: freq=382.2Hz, dur=1.32s (from training sample 8)
9: freq=494.5Hz, dur=0.88s (from training sample 9)
✓ Done! All files have DIFFERENT frequencies now!


rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.18 (double samples) Nov 24 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 48000.0, kr = 1500.000, ksmps = 32
0dBFS level = 1.0, A4 tuning = 440.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to  _temp_1.wav (WAV)
SECTION 1:
new alloc for instr 1:
B  0.000 ..  0.877 T  0.877 TT  0.877 M:  0.50000  0.50000
Score finished in csoundPerformKsmps() with 2.
inactive allocs returned to freespace
end of score.		   overall amps:  0.50000  0.50000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
2048 4096 sample blks of shorts written to  _temp_1.wav (WAV)
